### ISSUE TITLE
Not possible to enter username more than 4 characters

### ISSUE THREAD

**Issue by opheliagame** [status-im/ethberlin-embark#1]
So when trying to create a user, it is not possible because I can't enter a username more than 4 characters. Is there something I am missing?
![screenshot_20180810_151149](https://user-images.githubusercontent.com/21999998/43951164-05e29136-9cb0-11e8-8271-d4d31d384fe7.png)

**Comment by ujjwalagrawal17** [comment]
I am also stuck in it. Did you find the solution for this issue? @opheliagame

**Comment by opheliagame** [comment]
I didn't find how or why this was happening but I closed my browser, and stopped the embark process. Then after a few minutes when I started it again it worked properly.

**Comment by ujjwalagrawal17** [comment]
Cool ! Anyway I just removed the check to make it work.
